package ai.constant;

public class InputValidateKey {
    public final static String TOKEN_CAN_NOT_BE_NULL_OR_EMPTY = "TOKEN_CAN_NOT_BE_NULL_OR_EMPTY";
    public final static String ORGANIZATION_ID_CAN_NOT_BE_NULL_OR_EMPTY = "ORGANIZATION_ID_CAN_NOT_BE_NULL_OR_EMPTY";
    public final static String USERNAME_CAN_NOT_BE_NULL_OR_EMPTY = "USERNAME_CAN_NOT_BE_NULL_OR_EMPTY";
    public final static String PASSWORD_CAN_NOT_BE_NULL_OR_EMPTY = "PASSWORD_CAN_NOT_BE_NULL_OR_EMPTY";
    public final static String USER_SOURCE_CAN_NOT_BE_NULL_OR_EMPTY = "USER_SOURCE_CAN_NOT_BE_NULL_OR_EMPTY";
    public final static String INVALID_USER_SOURCE_VALUE = "INVALID_USER_SOURCE_VALUE";
    public final static String MESSAGE_CAN_NOT_BE_NULL_OR_EMPTY = "MESSAGE_CAN_NOT_BE_NULL_OR_EMPTY";
    public final static String RAG_SCOPE_CAN_NOT_BE_NULL_OR_EMPTY = "RAG_SCOPE_CAN_NOT_BE_NULL_OR_EMPTY";
    public final static String INVALID_RAG_SCOPE_VALUE = "INVALID_RAG_SCOPE_VALUE";
    public final static String NESTED_CHILD_VALUE_INVALID = "NESTED_CHILD_VALUE_INVALID";
    public final static String INVALID_SORT_DIR_VALUE = "INVALID_SORT_DIR_VALUE";
    public final static String INVALID_SORT_FIELD_VALUE = "INVALID_SORT_FIELD_VALUE";
    public final static String ORGANIZATION_NAME_CAN_NOT_BE_NULL_OR_EMPTY = "ORGANIZATION_NAME_CAN_NOT_BE_NULL_OR_EMPTY";
    public final static String PARENT_ORGANIZATION_ID_CAN_NOT_BE_NULL_OR_EMPTY = "PARENT_ORGANIZATION_ID_CAN_NOT_BE_NULL_OR_EMPTY";
    public final static String USER_IDS_CAN_NOT_BE_NULL_OR_EMPTY = "USER_IDS_CAN_NOT_BE_NULL_OR_EMPTY";
    public final static String ROLE_ID_CAN_NOT_BE_NULL = "ROLE_ID_CAN_NOT_BE_NULL";
    public final static String PERMISSION_NAME_CAN_NOT_BE_NULL_OR_EMPTY = "PERMISSION_NAME_CAN_NOT_BE_NULL_OR_EMPTY";
    public final static String PERMISSION_RESOURCE_CAN_NOT_BE_NULL_OR_EMPTY = "PERMISSION_RESOURCE_CAN_NOT_BE_NULL_OR_EMPTY";
    public final static String PERMISSION_ACTION_CAN_NOT_BE_NULL_OR_EMPTY = "PERMISSION_ACTION_CAN_NOT_BE_NULL_OR_EMPTY";
    public final static String INVALID_VALUE_PERMISSION_RESOURCE = "INVALID_VALUE_PERMISSION_RESOURCE";
    public final static String INVALID_VALUE_PERMISSION_ACTION = "INVALID_VALUE_PERMISSION_ACTION";
    public final static String ROLE_NAME_CAN_NOT_BE_NULL_OR_EMPTY = "ROLE_NAME_CAN_NOT_BE_NULL_OR_EMPTY";
    public final static String ROLE_PERMISSION_CAN_NOT_BE_NULL = "ROLE_PERMISSION_CAN_NOT_BE_NULL";
    public final static String ASSIGN_PERMISSION_ID_CAN_NOT_BE_NULL = "ASSIGN_PERMISSION_ID_CAN_NOT_BE_NULL";
    public final static String ASSIGN_PERMISSION_SCOPE_CAN_NOT_BE_NULL = "ASSIGN_PERMISSION_SCOPE_CAN_NOT_BE_NULL";
    public final static String INVALID_VALUE_PERMISSION_SCOPE = "INVALID_VALUE_PERMISSION_SCOPE";
    public final static String TOPIC_TITLE_CAN_NOT_BE_NULL_OR_EMPTY = "TOPIC_TITLE_CAN_NOT_BE_NULL_OR_EMPTY";
    public final static String TOPIC_TYPE_CAN_NOT_BE_NULL_OR_EMPTY = "TOPIC_TYPE_CAN_NOT_BE_NULL_OR_EMPTY";
    public final static String NOTEBOOK_TITLE_CAN_NOT_BE_NULL_OR_EMPTY = "NOTEBOOK_TITLE_CAN_NOT_BE_NULL_OR_EMPTY";
    public final static String USER_FIRST_NAME_CAN_NOT_BE_NULL_OR_EMPTY = "USER_FIRST_NAME_CAN_NOT_BE_NULL_OR_EMPTY";
    public final static String USER_GENDER_VALUE_INVALID = "USER_GENDER_VALUE_INVALID";
    public final static String USER_EMAIL_CAN_NOT_BE_NULL_OR_EMPTY = "USER_EMAIL_CAN_NOT_BE_NULL_OR_EMPTY";
    public final static String USER_EMAIL_VALUE_INVALID = "USER_EMAIL_VALUE_INVALID";
    public final static String USER_PASSWORD_CAN_NOT_BE_NULL_OR_EMPTY = "USER_PASSWORD_CAN_NOT_BE_NULL_OR_EMPTY";
    public final static String USER_PHONE_NUMBER_VALUE_INVALID = "USER_PHONE_NUMBER_VALUE_INVALID";
    public final static String INVALID_PASSWORD = "INVALID_PASSWORD";
    public final static String USER_NAME_CAN_NOT_BE_NULL_OR_EMPTY = "USER_NAME_CAN_NOT_BE_NULL_OR_EMPTY";
    public final static String INVALID_MESSAGE_PARENT_VALUE = "INVALID_MESSAGE_PARENT_VALUE";
    public final static String MESSAGE_CONTENT_CAN_NOT_BE_NULL_OR_EMPTY = "MESSAGE_CONTENT_CAN_NOT_BE_NULL_OR_EMPTY";
    public final static String MESSAGE_TYPE_CAN_NOT_BE_NULL_OR_EMPTY = "MESSAGE_TYPE_CAN_NOT_BE_NULL_OR_EMPTY";
    public final static String MESSAGE_PARENT_ID_CAN_NOT_BE_NULL_OR_EMPTY = "MESSAGE_PARENT_ID_CAN_NOT_BE_NULL_OR_EMPTY";
    public final static String MESSAGE_PARENT_TYPE_CAN_NOT_BE_NULL_OR_EMPTY = "MESSAGE_PARENT_TYPE_CAN_NOT_BE_NULL_OR_EMPTY";

    public final static String DATA_INGESTION_NAME_REQUIRED = "DATA_INGESTION_NAME_REQUIRED";
    public final static String DATA_INGESTION_ACCESS_LEVEL_INVALID = "DATA_INGESTION_ACCESS_LEVEL_INVALID";
    public final static String DATA_INGESTION_FROM_SOURCE_INVALID = "DATA_INGESTION_FROM_SOURCE_INVALID";
    public final static String DATA_INGESTION_FILE_REQUIRED = "DATA_INGESTION_FILE_REQUIRED";

    public final static String DRIVE_NAME_REQUIRED = "DRIVE_NAME_REQUIRED";
    public final static String DRIVE_FILE_REQUIRED = "DRIVE_FILE_REQUIRED";

    public final static String NOTE_CONTENT_CAN_NOT_BE_NULL_OR_EMPTY = "NOTE_CONTENT_CAN_NOT_BE_NULL_OR_EMPTY";
    public final static String NOTE_SOURCE_TYPE_CAN_NOT_BE_NULL_OR_EMPTY = "NOTE_SOURCE_TYPE_CAN_NOT_BE_NULL_OR_EMPTY";
    public final static String NOTE_SOURCE_TYPE_INVALID = "NOTE_SOURCE_TYPE_INVALID";
    public final static String NOTE_IDS_CAN_NOT_BE_NULL_OR_EMPTY = "NOTE_IDS_CAN_NOT_BE_NULL_OR_EMPTY";
}
