package ai.enums;

import lombok.AccessLevel;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.experimental.FieldDefaults;
import org.springframework.http.HttpStatus;
import org.springframework.http.HttpStatusCode;

@AllArgsConstructor
@Getter
@FieldDefaults(level = AccessLevel.PRIVATE, makeFinal = true)
public enum ApiResponseStatus {
    INVALID_SORT_FIELD_VALUE(1001, "Invalid sort field value", HttpStatus.BAD_REQUEST),
    INVALID_SORT_DIR_VALUE(1002, "Sort direction value only accept ASC/DESC", HttpStatus.BAD_REQUEST),
    USERNAME_CAN_NOT_BE_NULL_OR_EMPTY(1003, "Username cannot be null or empty", HttpStatus.BAD_REQUEST),
    PASSWORD_CAN_NOT_BE_NULL_OR_EMPTY(1004, "Password cannot be null or empty", HttpStatus.BAD_REQUEST),
    INVALID_PASSWORD(1005, "Password length must be at least 5 characters", HttpStatus.BAD_REQUEST),
    USER_SOURCE_CAN_NOT_BE_NULL_OR_EMPTY(1006, "Source cannot be null or empty", HttpStatus.BAD_REQUEST),
    INVALID_USER_SOURCE_VALUE(1006, "Invalid user source value", HttpStatus.BAD_REQUEST),
    TOKEN_CAN_NOT_BE_NULL_OR_EMPTY(1007, "Token cannot be null or empty", HttpStatus.BAD_REQUEST),
    PARENT_ORGANIZATION_NOT_EXISTS(1008, "Parent organization does not exist", HttpStatus.NOT_FOUND),
    ORGANIZATION_NOT_EXISTS(1009, "Organization does not exist", HttpStatus.NOT_FOUND),
    ORGANIZATION_NOT_EMPTY(1010, "Organization is not empty", HttpStatus.CONFLICT),
    ORGANIZATION_NAME_CAN_NOT_BE_NULL_OR_EMPTY(1011, "Organization name cannot be null or empty", HttpStatus.BAD_REQUEST),
    ORGANIZATION_ID_CAN_NOT_BE_NULL_OR_EMPTY(1012, "Organization id cannot be null or empty", HttpStatus.BAD_REQUEST),
    PARENT_ORGANIZATION_ID_CAN_NOT_BE_NULL_OR_EMPTY(1013, "Parent organization id cannot be null or empty", HttpStatus.BAD_REQUEST),
    ROOT_ORGANIZATION_NOT_EXIST(1014, "Root organization not exists!", HttpStatus.NOT_FOUND),
    NESTED_CHILD_VALUE_INVALID(1014, "Invalid nested child value!", HttpStatus.NOT_FOUND),
    USER_NOT_EXISTS(1015, "User does not exist", HttpStatus.NOT_FOUND),
    USER_EXISTED(1016, "User already exists", HttpStatus.CONFLICT),

    ROLE_NAME_CAN_NOT_BE_NULL_OR_EMPTY(1017, "Role name cannot be null or empty", HttpStatus.BAD_REQUEST),
    ROLE_NAME_EXISTED(1018, "Role name already exists", HttpStatus.CONFLICT),
    ROLE_ID_NOT_EXISTS(1019, "Role ID does not exist", HttpStatus.NOT_FOUND),
    ROLE_DEFAULT_ASSIGN_NOT_EXISTS(1020, "No role available for default assignment", HttpStatus.NOT_FOUND),
    ROLE_PERMISSION_CAN_NOT_BE_NULL(1021, "Role permissions cannot be null", HttpStatus.BAD_REQUEST),
    ROLE_ID_CAN_NOT_BE_NULL(1022, "Role ID cannot be null", HttpStatus.BAD_REQUEST),

    PERMISSION_NAME_CAN_NOT_BE_NULL_OR_EMPTY(1023, "Permission name cannot be null or empty", HttpStatus.BAD_REQUEST),
    PERMISSION_RESOURCE_CAN_NOT_BE_NULL_OR_EMPTY(1024, "Permission resource cannot be null or empty", HttpStatus.BAD_REQUEST),
    INVALID_VALUE_PERMISSION_RESOURCE(1025, "Invalid permission resource", HttpStatus.BAD_REQUEST),
    PERMISSION_ACTION_CAN_NOT_BE_NULL_OR_EMPTY(1026, "Permission action cannot be null or empty", HttpStatus.BAD_REQUEST),
    INVALID_VALUE_PERMISSION_ACTION(1027, "Invalid permission action", HttpStatus.BAD_REQUEST),
    PERMISSION_NAME_EXISTED(1028, "Permission name already exists", HttpStatus.CONFLICT),
    PERMISSION_ID_NOT_EXISTS(1029, "Permission ID does not exist", HttpStatus.NOT_FOUND),
    INVALID_VALUE_PERMISSION_SCOPE(1030, "Invalid permission scope", HttpStatus.BAD_REQUEST),
    ASSIGN_PERMISSION_ID_CAN_NOT_BE_NULL(1031, "Assign permission id cannot be null or empty", HttpStatus.BAD_REQUEST),
    ASSIGN_PERMISSION_SCOPE_CAN_NOT_BE_NULL(1032, "Assign permission scope cannot be null or empty", HttpStatus.BAD_REQUEST),

    USER_EXISTED_IN_ORGANIZATION(1033, "User already exists in organization", HttpStatus.CONFLICT),
    USER_WITH_ROLE_EXISTED_IN_ORGANIZATION(1034, "User with role already exists in organization", HttpStatus.CONFLICT),
    USER_WITH_ROLE_NOT_EXIST_IN_ORGANIZATION(1035, "User with role does not exist in organization", HttpStatus.NOT_FOUND),
    USER_NOT_EXIST_IN_ORGANIZATION(1036, "User does not exist in organization", HttpStatus.NOT_FOUND),
    USER_MUST_HAVE_AT_LEAST_ONE_ROLE_IN_ORGANIZATION(1037, "User must have at least one role in the organization", HttpStatus.BAD_REQUEST),
    USER_NAME_CAN_NOT_BE_NULL_OR_EMPTY(1038, "User name cannot be null or empty", HttpStatus.BAD_REQUEST),
    USER_FIRST_NAME_CAN_NOT_BE_NULL_OR_EMPTY(1039, "User first name cannot be null or empty", HttpStatus.BAD_REQUEST),
    USER_PASSWORD_CAN_NOT_BE_NULL_OR_EMPTY(1040, "User password cannot be null or empty", HttpStatus.BAD_REQUEST),
    USER_PASSWORD_INCORRECT(1041, "User password incorrect", HttpStatus.BAD_REQUEST),
    USER_GENDER_VALUE_INVALID(1042, "User gender must be 0 (male) or 1 (female)", HttpStatus.BAD_REQUEST),
    USER_EMAIL_VALUE_INVALID(1043, "User email is invalid", HttpStatus.BAD_REQUEST),
    USER_PHONE_NUMBER_VALUE_INVALID(1043, "User phone number is invalid", HttpStatus.BAD_REQUEST),
    USER_EMAIL_CAN_NOT_BE_NULL_OR_EMPTY(1044, "Email cannot be null or empty", HttpStatus.BAD_REQUEST),
    ONLY_LOCAL_USER_CAN_UPDATE_INFO(1045, "Only local user can update", HttpStatus.BAD_REQUEST),
    USER_IDS_CAN_NOT_BE_NULL_OR_EMPTY(1046, "User IDs cannot be null or empty", HttpStatus.BAD_REQUEST),
    ROOT_USER_NOT_EXIST(1014, "Root user not exists!", HttpStatus.NOT_FOUND),

    TOPIC_ID_NOT_EXISTS(1047, "Topic ID does not exist", HttpStatus.NOT_FOUND),
    TOPIC_TITLE_CAN_NOT_BE_NULL_OR_EMPTY(1048, "Topic title cannot be null or empty", HttpStatus.BAD_REQUEST),
    TOPIC_TYPE_CAN_NOT_BE_NULL_OR_EMPTY(1049, "Topic type cannot be null or empty", HttpStatus.BAD_REQUEST),

    NOTEBOOK_ID_NOT_EXISTS(1047, "Notebook ID does not exist", HttpStatus.NOT_FOUND),
    NOTEBOOK_TITLE_CAN_NOT_BE_NULL_OR_EMPTY(1048, "Notebook title cannot be null or empty", HttpStatus.BAD_REQUEST),
    INVALID_MESSAGE_PARENT_VALUE(1049, "Invalid message parent value", HttpStatus.BAD_REQUEST),

    MESSAGE_PARENT_TYPE_CAN_NOT_BE_NULL_OR_EMPTY(1049, "Message parent type cannot be null or empty", HttpStatus.BAD_REQUEST),
    MESSAGE_PARENT_ID_CAN_NOT_BE_NULL_OR_EMPTY(1049, "Message parent id cannot be null or empty", HttpStatus.BAD_REQUEST),
    MESSAGE_TYPE_CAN_NOT_BE_NULL_OR_EMPTY(1049, "Message type cannot be null or empty", HttpStatus.BAD_REQUEST),
    MESSAGE_CONTENT_CAN_NOT_BE_NULL_OR_EMPTY(1049, "Message content cannot be null or empty", HttpStatus.BAD_REQUEST),

    MESSAGE_ID_NOT_EXISTS(1050, "Topic ID does not exist", HttpStatus.NOT_FOUND),
    MESSAGE_CAN_NOT_BE_NULL_OR_EMPTY(1051, "Message cannot be null or empty", HttpStatus.BAD_REQUEST),
    RAG_SCOPE_CAN_NOT_BE_NULL_OR_EMPTY(1052, "Scope cannot be null or empty", HttpStatus.BAD_REQUEST),
    INVALID_RAG_SCOPE_VALUE(1053, "Invalid scope value", HttpStatus.BAD_REQUEST),
    UNAUTHENTICATED(1054, "Unauthenticated", HttpStatus.UNAUTHORIZED),
    PERMISSION_DENIED(1055, "You do not have permission", HttpStatus.FORBIDDEN),
    USER_NOT_IN_ORG(1056, "User is not in any organization", HttpStatus.FORBIDDEN),
    TOKEN_INVALID(1057, "Invalid token", HttpStatus.UNAUTHORIZED),
    AUTHENTICATE_FAILED(1058, "Authentication failed", HttpStatus.UNAUTHORIZED),
    REQUEST_METHOD_NOT_ALLOWED(1059, "Request method not allowed", HttpStatus.METHOD_NOT_ALLOWED),
    INVALID_REQUEST_INFORMATION(1060, "Invalid request information", HttpStatus.BAD_REQUEST),
    DATA_INGESTION_JOB_ID_NOT_EXISTS(1061, "Data ingestion job id not exists", HttpStatus.BAD_REQUEST),
    INGESTION_SERVICE_UNAVAILABLE(1062, "Ingestion service unavailable", HttpStatus.BAD_REQUEST),
    DATA_INGESTION_PARENT_NOT_EXISTS(1063, "Data ingestion parent not exists", HttpStatus.BAD_REQUEST),
    DATA_INGESTION_FILE_REQUIRED(1064, "Data ingestion file is required", HttpStatus.BAD_REQUEST),
    DATA_INGESTION_ACCESS_LEVEL_INVALID(1065, "Data ingestion access level is invalid", HttpStatus.BAD_REQUEST),
    DATA_INGESTION_TARGET_INVALID(1066, "Data ingestion target is invalid", HttpStatus.BAD_REQUEST),
    DATA_INGESTION_ORG_ID_REQUIRED(1067, "Data ingestion org id is required", HttpStatus.BAD_REQUEST),
    DATA_INGESTION_OWNER_ID_REQUIRED(1068, "Data ingestion owner id is required", HttpStatus.BAD_REQUEST),
    DATA_INGESTION_UNIT_REQUIRED(1069, "Data ingestion unit is required", HttpStatus.BAD_REQUEST),
    DATA_INGESTION_USERNAME_REQUIRED(1070, "Data ingestion username is required", HttpStatus.BAD_REQUEST),
    DATA_INGESTION_UPLOAD_FAILED(1071, "Data ingestion upload failed", HttpStatus.BAD_REQUEST),
    DATA_INGESTION_DOWNLOAD_FAILED(1072, "Data ingestion download failed", HttpStatus.BAD_REQUEST),
    DATA_INGESTION_NOT_EXISTS(1073, "Data ingestion not exists", HttpStatus.BAD_REQUEST),
    DATA_INGESTION_RETRY_ONLY_FAILED(1074, "Only failed data ingestion can retry ingestion", HttpStatus.BAD_REQUEST),
    DATA_INGESTION_NAME_REQUIRED(1075, "Data ingestion name is required", HttpStatus.BAD_REQUEST),
    DATA_INGESTION_FROM_SOURCE_INVALID(1105, "Data ingestion from source is invalid", HttpStatus.BAD_REQUEST),
    DATA_INGESTION_RETRY_ONLY_INGESTION_TARGET(1076, "Only ingestion target data ingestion can retry", HttpStatus.BAD_REQUEST),
    DATA_INGESTION_SORT_BY_INVALID(1077, "Data ingestion sort field is invalid", HttpStatus.BAD_REQUEST),
    DATA_INGESTION_SORT_DIR_INVALID(1078, "Data ingestion sort direction is invalid", HttpStatus.BAD_REQUEST),
    DATA_INGESTION_FOLDER_ONLY_OPERATION(1079, "This operation is only for folder", HttpStatus.BAD_REQUEST),
    DATA_INGESTION_PARENT_MUST_BE_FOLDER(1080, "Data ingestion parent must be folder", HttpStatus.BAD_REQUEST),
    DATA_INGESTION_MOVE_CYCLE_NOT_ALLOWED(1081, "Data ingestion move cycle is not allowed", HttpStatus.BAD_REQUEST),
    DATA_INGESTION_FOLDER_UPDATE_REQUIRED(1082, "Data ingestion folder update payload is empty", HttpStatus.BAD_REQUEST),
    DATA_INGESTION_DELETE_FAILED(1083, "Data ingestion delete failed", HttpStatus.BAD_REQUEST),
    DATA_INGESTION_DELETE_IN_PROGRESS(1084, "Data ingestion deletion is in progress", HttpStatus.CONFLICT),
    DATA_INGESTION_NOT_COMPLETED(1110, "Data ingestion must be completed before this operation", HttpStatus.CONFLICT),
    DRIVE_PARENT_NOT_EXISTS(1085, "Drive parent not exists", HttpStatus.BAD_REQUEST),
    DRIVE_FILE_REQUIRED(1086, "Drive file is required", HttpStatus.BAD_REQUEST),
    DRIVE_UPLOAD_FAILED(1087, "Drive upload failed", HttpStatus.BAD_REQUEST),
    DRIVE_DOWNLOAD_FAILED(1088, "Drive download failed", HttpStatus.BAD_REQUEST),
    DRIVE_NOT_EXISTS(1089, "Drive not exists", HttpStatus.BAD_REQUEST),
    DRIVE_NAME_REQUIRED(1090, "Drive name is required", HttpStatus.BAD_REQUEST),
    DRIVE_SORT_BY_INVALID(1091, "Drive sort field is invalid", HttpStatus.BAD_REQUEST),
    DRIVE_SORT_DIR_INVALID(1092, "Drive sort direction is invalid", HttpStatus.BAD_REQUEST),
    DRIVE_FOLDER_ONLY_OPERATION(1093, "This operation is only for drive folder", HttpStatus.BAD_REQUEST),
    DRIVE_PARENT_MUST_BE_FOLDER(1094, "Drive parent must be folder", HttpStatus.BAD_REQUEST),
    DRIVE_MOVE_CYCLE_NOT_ALLOWED(1095, "Drive move cycle is not allowed", HttpStatus.BAD_REQUEST),
    DRIVE_FOLDER_UPDATE_REQUIRED(1096, "Drive folder update payload is empty", HttpStatus.BAD_REQUEST),
    DRIVE_DELETE_FAILED(1097, "Drive delete failed", HttpStatus.BAD_REQUEST),
    DRIVE_DELETE_IN_PROGRESS(1098, "Drive deletion is in progress", HttpStatus.CONFLICT),
    ATTACHMENT_NOT_EXISTS(1099, "Attachment does not exist", HttpStatus.NOT_FOUND),
    ATTACHMENT_FILE_REQUIRED(1100, "Attachment file is required", HttpStatus.BAD_REQUEST),
    ATTACHMENT_UPLOAD_FAILED(1101, "Attachment upload failed", HttpStatus.BAD_REQUEST),
    ATTACHMENT_DOWNLOAD_FAILED(1102, "Attachment download failed", HttpStatus.BAD_REQUEST),
    ATTACHMENT_SORT_BY_INVALID(1103, "Attachment sort field is invalid", HttpStatus.BAD_REQUEST),
    ATTACHMENT_SORT_DIR_INVALID(1104, "Attachment sort direction is invalid", HttpStatus.BAD_REQUEST),

    TOPIC_SOURCE_ALREADY_EXISTS(1106, "Topic source already exists", HttpStatus.CONFLICT),
    TOPIC_SOURCE_NOT_EXISTS(1107, "Topic source does not exist", HttpStatus.NOT_FOUND),
    NOTEBOOK_SOURCE_ALREADY_EXISTS(1108, "Notebook source already exists", HttpStatus.CONFLICT),
    NOTEBOOK_SOURCE_NOT_EXISTS(1109, "Notebook source does not exist", HttpStatus.NOT_FOUND),
    NOTEBOOK_SOURCE_PAYLOAD_REQUIRED(1110, "Notebook source payload must include file(s), textContent, or noteId", HttpStatus.BAD_REQUEST),
    NOTEBOOK_SOURCE_JOB_ID_NOT_EXISTS(1121, "Notebook source job id not exists", HttpStatus.BAD_REQUEST),
    NOTEBOOK_SOURCE_DELETE_IN_PROGRESS(1122, "Notebook source deletion is in progress", HttpStatus.CONFLICT),
    NOTEBOOK_SOURCE_DELETE_FAILED(1123, "Notebook source delete failed", HttpStatus.BAD_REQUEST),
    TOPIC_SOURCE_PAYLOAD_REQUIRED(1120, "Topic source payload must include file(s)", HttpStatus.BAD_REQUEST),

    NOTE_NOT_EXISTS(1111, "Note does not exist", HttpStatus.NOT_FOUND),
    NOTE_CONTENT_CAN_NOT_BE_NULL_OR_EMPTY(1112, "Note content cannot be null or empty", HttpStatus.BAD_REQUEST),
    NOTE_SOURCE_TYPE_CAN_NOT_BE_NULL_OR_EMPTY(1113, "Note source type cannot be null or empty", HttpStatus.BAD_REQUEST),
    NOTE_SOURCE_TYPE_INVALID(1114, "Invalid note source type", HttpStatus.BAD_REQUEST),
    NOTE_SOURCE_TARGET_INVALID(1115, "Note source target is invalid", HttpStatus.BAD_REQUEST),
    NOTE_TOPIC_ID_REQUIRED(1116, "Topic id is required for TOPIC note source", HttpStatus.BAD_REQUEST),
    NOTE_NOTEBOOK_ID_REQUIRED(1117, "Notebook id is required for NOTEBOOK note source", HttpStatus.BAD_REQUEST),
    NOTE_SORT_BY_INVALID(1118, "Note sort field is invalid", HttpStatus.BAD_REQUEST),
    NOTE_SORT_DIR_INVALID(1119, "Note sort direction is invalid", HttpStatus.BAD_REQUEST),

    UNEXPECTED(9999, "An unexpected error occurred!",HttpStatus.INTERNAL_SERVER_ERROR);

    int code;
    String message;
    HttpStatusCode httpStatusCode;
}
 