spring:
  datasource:
    url: "jdbc:postgresql://192.168.30.72:5432/core_service_2"
    username: "postgres"
    password: "P@ssw0rd"



integration:
  attachment-api:
    header-name: "X-API-KEY"
    key: "ATTACHMENT_API_KEY_1234567890"
  data-ingestion-api:
    header-name: "X-API-KEY"
    key: "DATA_INGESTION_API_KEY_1234567890"
  data-ingestion-callback:
    # URL để ingestion service callback trạng thái về core service
    url: "http://192.168.10.103:8080/api/v1/user/data-ingestion/ingestion/webhook/status"
    # Shared secret dùng để xác thực webhook callback (máy chủ gọi về phải gửi đúng giá trị này)
    signature: "ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890"
    # Có thể gửi signature qua query param, ví dụ: ?signature=YOUR_WEBHOOK_SHARED_SECRET
    signature-param-name: "signature"
    # Hoặc gửi qua header, ví dụ: X-Webhook-Signature: YOUR_WEBHOOK_SHARED_SECRET
    signature-header-name: "X-Webhook-Signature"
  notebook-source-callback:
    # URL để ingestion service callback trạng thái notebook source về core service
    url: "http://192.168.10.103:8080/api/v1/user/notebooks/sources/ingestion/webhook/status"
    # Shared secret dùng để xác thực webhook callback notebook source
    signature: "ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890"
    # Có thể gửi signature qua query param, ví dụ: ?signature=YOUR_WEBHOOK_SHARED_SECRET
    signature-param-name: "signature"
    # Hoặc gửi qua header, ví dụ: X-Webhook-Signature: YOUR_WEBHOOK_SHARED_SECRET
    signature-header-name: "X-Webhook-Signature"