server.port=8080

spring.application.name=NGN AI core

logging.level.org.springframework.jdbc.core=DEBUG
logging.file.name=application.log
logging.file.path=logs

spring.datasource.url=jdbc:postgresql://192.168.30.72:5432/core_service
spring.datasource.username=postgres
spring.datasource.password=P@ssw0rd
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

sql.init.mode=always

jwt.secret-key=2daEri6ObwgO7dlnqH8SlcgtKWQ1njWdkg7hFv+gjTlfxxaeqBdg7XimfhBEIJEn
jwt.expiry-duration=216000