server.port=8080

spring.application.name=NGN AI core

logging.level.org.springframework.jdbc.core=DEBUG
logging.file.name=application.log
logging.file.path=logs

spring.datasource.url=jdbc:postgresql://192.168.30.72:5432/core_service
spring.datasource.username=postgres
spring.datasource.password=P@ssw0rd
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

jpa.hibernate.ddl-auto=update
jpa.show-sql=true
jpa.properties.hibernate.format_sql=true

sql.init.mode=always